### ISSUE TITLE
Inappropriate structure definition prefix "PLD_"

### ISSUE THREAD

**Issue by niruiyu** [UniversalScalableFirmware/documentation#21]
In https://edk2.groups.io/g/devel/message/76229?p=,,,20,0,0,0::Created,,UNIVERSAL_PAYLOAD,20,2,0,83304942, Mike Kinney recommended using UNIVERSAL_PAYLOAD or PAYLOAD as the structure definition prefix because "PLD" sometimes is interpreted as Programmable Logic Device.

"PAYLOAD_" prefix works for me.

Comments?

**Comment by gdong1** [comment]
I am also OK to use the full name "PAYLOAD" instead of "PLD"

**Comment by mauricema** [comment]
I vote for "UNIVERSAL_PAYLOAD" to make it more specific.  There might be new payload later on.

**Comment by niruiyu** [comment]
Maurice, that's a good reason for "UNIVERSAL_PAYLOAD".
Guo, ok to use "UNIVERSAL_PAYLOAD"?

**Comment by gdong1** [comment]
yes. "UNIVERSAL_PAYLOAD" also fine for me.

**Comment by gdong1** [comment]
close this issue since specification was updated to use "UNIVERSAL_PAYLOAD" instead of "PLD"
